# **NLP basic**

In [1]:
#token -> 가장 작인 단위
#token을 만들어 내는 것이 toeknizing

#한국어 tokenizing이 많이 어렵다.

#대표적인 KoNLPy자연어처리 토크나이징 지원 모듈

#형태소 의미를 고려해서 형태소를 분석한다.(품사 표현한 단어oken -> 가장 작인 단위
#token을 만들어 내는 것이 toeknizing

#한국어 tokenizing이 많이 어렵다.

#대표적인 KoNLPy자연어처리 토크나이징 지원 모듈

#형태소 의미를 고려해서 형태소를 분석한다.(품사 표현한 단어)

#Kkma 라이센스 -> KoNLPy에서 불러서 사용해야한다.
#꼬꼬마 한국어 형태소 분석기 사이트 품사 태그표 즐겨찾기 하기!!

#반환 형태가 list인지 list의 list인지 잘 봐야한다.

토큰화사용

In [2]:
pip install konlpy

     |████████████████████████████████| 19.4MB 1.4MB/s 
     |████████████████████████████████| 92kB 8.8MB/s 
     |████████████████████████████████| 460kB 42.0MB/s 
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


**1. Kkma 사용**

In [3]:
from konlpy.tag import Kkma

kkma = Kkma()


In [4]:
text="코스피 지수가 3200을 돌파하였다."

In [5]:
#형태소 추출 method -> 토큰나이징 하는 함수
morphs = kkma.morphs(text)
print(morphs)

['코스', '피', '지수', '가', '3200', '을', '돌파', '하', '였', '다', '.']


In [6]:
#각 형태소마다 품사 추출(tagging)
pos = kkma.pos(text)
print(pos)

[('코스', 'NNG'), ('피', 'NNG'), ('지수', 'NNG'), ('가', 'JKS'), ('3200', 'NR'), ('을', 'JKO'), ('돌파', 'NNG'), ('하', 'XSV'), ('였', 'EPT'), ('다', 'EFN'), ('.', 'SF')]


In [7]:
text = "코스피 지수가 3200을 돌파하였다! 내 계좌가 행복하다."

In [8]:
#문장 분리 추출(sentences)
#첫번째 문장 마무리 기호(!,. 등) 안 넣어주면 안 나뉘넹
sent = kkma.sentences(text)
print(sent)

['코스 피 지수가 3200을 돌파하였다!', '내 계좌가 행복하다.']


**2. Komoran**

In [9]:
#Komoran 불러오기

#코모란 java 기반 형태소 분석
#https://www.shineware.co.kr/products/komoran/#demo?utm_source=komoran-kr&utm_medium=Referral&utm_campaign=github-demo

from konlpy.tag import Komoran
komoran=Komoran()

text = "최고의 코딩 프로그램 코드라이언."



In [10]:
sent_=komoran.morphs(text)
print("morphs() : ",sent_)

nouns_ = komoran.nouns(text)
print("nouns() : ",nouns_)

pos_ = komoran.pos(text)
print("pos() : ",pos_)

morphs() :  ['최고', '의', '코', '딩', '프로그램', '코드', '라이언', '.']
nouns() :  ['최고', '코', '프로그램', '코드', '라이언']
pos() :  [('최고', 'NNG'), ('의', 'JKG'), ('코', 'NNG'), ('딩', 'MAG'), ('프로그램', 'NNG'), ('코드', 'NNP'), ('라이언', 'NNP'), ('.', 'SF')]


In [13]:
#코모란은 사전을 추가할 수 있는 기능이 있음
from konlpy.tag import Komoran
#tsv는 메모장을 만들어서 해도 됨
#tsv 파일은 tap을 기반으로 나뉨
komoran=Komoran(userdic='/content/user_dic.tsv') #이 tsv파일에서 코드라이언을 하나의 NNG로 보라고 설정

text = "최고의 코딩 프로그램 코드라이언."

In [14]:
#코드라이언 등이 붙어서 나온다. -> 노가다라 힘든 것이 있음
sent_=komoran.morphs(text)
print("morphs() : ",sent_)

nouns_ = komoran.nouns(text)
print("nouns() : ",nouns_)

pos_ = komoran.pos(text)
print("pos() : ",pos_)
#'코드라이언'을 하나의 NNG로 보고 있다.

morphs() :  ['최고', '의', '코딩', '프로그램', '코드라이언', '.']
nouns() :  ['최고', '코딩', '프로그램', '코드라이언']
pos() :  [('최고', 'NNG'), ('의', 'JKG'), ('코딩', 'NNG'), ('프로그램', 'NNG'), ('코드라이언', 'NNG'), ('.', 'SF')]


**3. Okt**

In [15]:
#구어체를 받으면 많은 변수가 있는데 -> normalize으로 처리한다.
#기능이 그렇게 좋지는 않다.

#phrases -> 어구를 추출
#Okt는 속도가 빠르고 normalize로 일정단위로 전처리가 가능하다.
#-> 단어 추가 기능이 없다.

#사전을 추가하고 싶다면 하드코딩하는 method 2개 붙여주는 함수를 만들어 준다.


In [16]:
from konlpy.tag import Okt
okt = Okt()

In [17]:
text = "게임 한판 할랙? ㅋㅋㅋㅋ. 사랑햌ㅋㅋㅋ, 뭐햄ㅋ"
morphs=okt.morphs(text)
print("morphs() : ", morphs)

normalize = okt.normalize(text)
print("normalize () : ",normalize)

morphs() :  ['게임', '한판', '할랙', '?', 'ㅋㅋㅋㅋ', '.', '사랑', '햌', 'ㅋㅋㅋ', ',', '뭐햄', 'ㅋ']
normalize () :  게임 한판 할랙? ㅋㅋㅋ. 사랑해ㅋㅋㅋ, 뭐햄ㅋ


**4. 챗봇에서도 위와같이 Komoran을 이용해 형태소 분석하는 경우가 많다.**

**5. 임베딩**

In [18]:
from konlpy.tag import Komoran
import numpy as np
komoran = Komoran(userdic='/content/user_dic.tsv')
text = "코드라이언 채널 좋아요 구독 알림설정까지"

#위의 text에서 명사만 추출
nouns = komoran.nouns(text)
print(nouns)

#단어 사전 구축 및 단어별 인덱스 부여
#단어별로 인덱스를 부여해 dictionary의 key와 value에 저장
#이미 저정한 것은 다시 사전에 저장 X
dics={}
for word in nouns:
  if word not in dics.keys():
    dics[word]=len(dics)
print(dics)

['코드라이언', '채널', '구독', '설정']
{'코드라이언': 0, '채널': 1, '구독': 2, '설정': 3}


In [19]:
#원-핫 인코딩
#dictionary type을 list 형태로 변환
nb_classes = len(dics)
targets = list(dics.values())
#np.eye() 함수를 통해 단위행렬을 만들어준다.
one_hot_targets = np.eye(nb_classes)[targets]
print(one_hot_targets)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
