# 1. 간단한 simpleRNN을 이용한 숫자 예측

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
#시퀀스 예측 데이터 생성
X=[]
Y=[]

#학습 데이터 만들기
for i in range(6):
  # [0,1,2,3] 등의 정수 시퀀스 만들기

  lst = list(range(i,i+4))

  #시퀀스의 숫자들을 각각 10으로 나누어 분리하여 배열에 저장
  X.append(list(map(lambda c : [c/10],lst)))
  #정답에 해당하는 정수 저장
  Y.append((i+4)/10)

X=np.array(X)
Y=np.array(Y)
for i in range(len(X)):
  print(X[i], Y[i])


[[0. ]
 [0.1]
 [0.2]
 [0.3]] 0.4
[[0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6
[[0.3]
 [0.4]
 [0.5]
 [0.6]] 0.7
[[0.4]
 [0.5]
 [0.6]
 [0.7]] 0.8
[[0.5]
 [0.6]
 [0.7]
 [0.8]] 0.9


In [4]:
#시퀀스 예측 모델 정의

#input_shape = [timesteps,input_dim]
#return_sequence -> 다음 계층으로 보내준다.(True 할 경우)

model = tf.keras.Sequential([
                             tf.keras.layers.SimpleRNN(units=10,return_sequences=False,input_shape=[4,1]),
                             #완전 연결 계층
                             tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam',loss='mse')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 10)                120       
_________________________________________________________________
dense (Dense)                (None, 1)                 11        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [5]:
#X는 [1,4,1]차원의 벡터

model.fit(X,Y,epochs=100,verbose=0)
model.save('simple_rnn_1.h5')
print(model.predict(X))

[[0.46169472]
 [0.5844375 ]
 [0.6628818 ]
 [0.7118065 ]
 [0.7438177 ]
 [0.7670337 ]]


In [6]:
print(model.predict(np.array([[[0.6],[0.7],[0.8],[0.9]]])))

[[0.7861601]]


In [7]:
print(model.predict(np.array([[[-0.1],[0.0],[0.1],[0.2]]])))

[[0.28988278]]


훈련 결과는 그렇게 좋지 못하다는 것을 알 수 있다.